/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bloomtech;

import java.io.InputStream;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

public class App {

    private static final float KNOT_TO_MPH_CONVERSION_FACTOR = 1.15f;

    public String getRawTextFromFile(String filename) {
        try {
            InputStream is = this.getClass().getClassLoader().getResourceAsStream(filename);
            String result = new BufferedReader(new InputStreamReader(is)).lines().collect(Collectors.joining("\n"));
            return result;
        } catch (Exception e) {
            throw new RuntimeException("Unable to read file", e);
        }
    }

    public List<String> splitLines(String rawHeadings) {
        // TODO: implement
        return null;
    }

    public List<String> filterHeadingsFromLines(List<String> lines) {
        // TODO: implement
        return null;
    }

    public Heading buildHeadingFromHeadingString(String headingString) {
        // TODO: implement
        return null;
    }

    public List<Heading> getHeadingsFromHeadingStrings(List<String> headingStrings) {
        // TODO: implement
        return null;
    }

    public float computeTotalDistanceTraveledInMiles(List<Heading> headings) {
        // TODO: implement
        return 0.0f;
    }

    public static void main(String[] args) {
        App app = new App();
        // TODO: compose all functions as required to compute total distance traveled in miles
    }
}
